### PR TITLE
remove redundant mount/3 in profile_live, closes #1049

### LINKED ISSUE #1049: Refactor the mount/3 functions in profile_live

### PR DESCRIPTION
**Pull request by briankariuki**
I've removed some redundant mount/3 code as its covered by the profile_socket functions. I've tested it both logged in and logged out and it works.

### CODE REVIEW

**Comment by MICHAELMUNAVU83** [comment]
@briankariuki  , This was there for if someone logs out but there is a cache , so the system thinks there is a `current_user` but there is none , it broke the system , that is why it was there .

**Comment by briankariuki** [comment]
> @briankariuki , This was there for if someone logs out but there is a cache , so the system thinks there is a `current_user` but there is none , it broke the system , that is why it was there .

How can I recreate this scenario?

**Comment by MICHAELMUNAVU83** [comment]
That was the problem actually , it is a sort of scenario we cannot replicate or test for , it happens sometimes when a cache happens , might you know how to simulate a cache

**Comment by MICHAELMUNAVU83** [comment]
@briankariuki  , here is the issue https://github.com/animina-dating/animina/issues/677

**Comment by wintermeyer** [comment]
> @briankariuki , here is the issue #677

With that information @briankariuki can replicate the problem. Build one system. Log in. Reset the database. Et voila!

**Comment by wintermeyer** [comment]
But: One can argue that this problem never occurs in the real world since we don't reset production every day. So I would be open to accept this problem since it is only relevant on development systems.

**Comment by briankariuki** [comment]
> But: One can argue that this problem never occurs in the real world.

True. I think we can close this

**Review by wintermeyer — APPROVED** [review]
@briankariuki Please do test this in production when we deploy it and have an eye on it 3-4 days after deployment. I don't want to be surprised by a bug we didn't see coming.

**Comment by wintermeyer** [comment]
@briankariuki I just triggered a deployment to production. You can see the time of the last commit of a production version in the footer (it is encoded in the version number).

**Comment by briankariuki** [comment]
> @briankariuki I just triggered a deployment to production. You can see the time of the last commit of a production version in the footer (it is encoded in the version number).

Will check in a few days

**Comment by wintermeyer** [comment]
> Will check in a few days

Please do check today too.

**Pull request merged**
