### PR TITLE
add action to get intersecting flags, closes #1056

### LINKED ISSUE #1056: Add action to user_flags that loads the intersecting flags between two users based on color

### PR DESCRIPTION
**Pull request by briankariuki**
I have added an action which uses only 1 sql query to get intersecting flags for two users based on color.
The action uses Ecto.Query instead of Ash.Query, enabling subqueries (to load flag and flag_translations), joins and grouping at the data_layer.
Suggestions to improve this action are welcome.

### CODE REVIEW

**Comment by wintermeyer** [comment]
> which uses only 1 sql query to get intersecting flags for two users

Just out of curiosity: How many SQL queries did we need before?

**Review by wintermeyer — APPROVED** [review]
Great work!

Please just fix the credo stuff.

**Comment by briankariuki** [comment]
> > which uses only 1 sql query to get intersecting flags for two users
> 
> Just out of curiosity: How many SQL queries did we need before?

number of user_flags x 2(1 for flag, 1 for flag_translation) per user. 

And these would be called a few times in the profile_live mount

**Comment by wintermeyer** [comment]
> And these would be called a few times in the profile_live mount

👍

Next step: We have to get rid of those translations. See https://github.com/animina-dating/animina/issues/1002

**Comment by briankariuki** [comment]
> Great work!
> 
> Please just fix the credo stuff.

For some reason running `mix credo --strict` results in an error

image

**Comment by wintermeyer** [comment]
> For some reason running `mix credo --strict` results in an error

Strange. It runs through in GitHub.

**Pull request merged**
