### PR TITLE
Adds resources to handle flags.

### PR DESCRIPTION
**Pull request by wintermeyer**

### CODE REVIEW

**Comment by wintermeyer** [comment]
@briankariuki @philipp-kempgen Run `mix format priv/repo/flag_seeds.exs` to seed the flags. This is the beginning of a green/red flag system.

**Comment by philipp-kempgen** [comment]
> @briankariuki @philipp-kempgen Run `mix format priv/repo/flag_seeds.exs` to seed the flags. This is the beginning of a green/red flag system.

By looking at [the Readme](https://github.com/animina-dating/animina/blob/d87cd2bd530f558f9b6449854be32f1000a106b4/README.md#database-migrations) it seems `mix ash_postgres.create && mix ash_postgres.migrate` as used in [docker-entrypoint.sh](https://github.com/animina-dating/animina/blob/d87cd2bd530f558f9b6449854be32f1000a106b4/docker-entrypoint.sh) won't run this automatically, right?

Are you sure `mix format ...` is the right tool?

**Comment by wintermeyer** [comment]
> > @briankariuki @philipp-kempgen Run `mix format priv/repo/flag_seeds.exs` to seed the flags. This is the beginning of a green/red flag system.
> 
> By looking at [the Readme](https://github.com/animina-dating/animina/blob/d87cd2bd530f558f9b6449854be32f1000a106b4/README.md#database-migrations) it seems `mix ash_postgres.create && mix ash_postgres.migrate` as used in [docker-entrypoint.sh](https://github.com/animina-dating/animina/blob/d87cd2bd530f558f9b6449854be32f1000a106b4/docker-entrypoint.sh) won't run this automatically, right?

Correct. They don't. Yet. I am not sure what the best way is for this right now.

> Are you sure `mix format ...` is the right tool?

I don't understand your question.

**Comment by philipp-kempgen** [comment]
> > Are you sure `mix format ...` is the right tool?
> 
> I don't understand your question.

I think what you meant to write was something like "`mix run priv/repo/flag_seeds.exs`" instead of "`mix format ...`".

**Comment by wintermeyer** [comment]
> I think what you meant to write was something like "`mix run priv/repo/flag_seeds.exs`" instead of "`mix format ...`".

Maybe. But I still don't fully understand what you are talking about. I used `mix format ...` as an ill advised headline of a paragraph. I just fixed that.

**Comment by philipp-kempgen** [comment]
You've lost me.
Anyways, "`mix run priv/repo/flag_seeds.exs`" is what runs the seeds.
I have added that to `docker-entrypoint.sh` in #92.

Slightly inconvenient: I need to run:
`mix run priv/repo/flag_seeds.exs || true`
because the seeds are not idempotent.
That means you get errors every single time you run `docker-compose up` after the initial run.

```
animina-web-1  | begin []
animina-web-1  | ↳ anonymous fn/3 in Ash.Changeset.with_hooks/3, at: lib/ash/changeset/changeset.ex:2186
animina-db-1   | ERROR:  duplicate key value violates unique constraint "traits_categories_unique_name_index"
animina-db-1   | DETAIL:  Key (name)=(sports) already exists.
animina-db-1   | STATEMENT:  INSERT INTO "traits_categories" ("id","name") VALUES ($1,$2) RETURNING "name","id"
animina-web-1  | [debug] QUERY ERROR source="traits_categories" db=18.5ms
animina-web-1  | INSERT INTO "traits_categories" ("id","name") VALUES ($1,$2) RETURNING "name","id" ["0ee9a74b-21bb-48d2-8d91-bdf536e730c9", #Ash.CiString<"sports">]
animina-web-1  | ↳ AshPostgres.DataLayer.bulk_create/3, at: lib/data_layer.ex:1412
animina-web-1  | [debug] QUERY OK db=3.3ms
animina-web-1  | rollback []
animina-web-1  | ↳ anonymous fn/3 in Ash.Changeset.with_hooks/3, at: lib/ash/changeset/changeset.ex:2186
animina-web-1  | ** (Ash.Error.Invalid) Input Invalid
animina-web-1  |
animina-web-1  | * Invalid value provided for name: has already been taken.
animina-web-1  |
animina-web-1  | nil
animina-web-1  |
animina-web-1  |     (ash 2.18.2) lib/ash/api/api.ex:2711: Ash.Api.unwrap_or_raise!/3
animina-web-1  |     priv/repo/flag_seeds.exs:857: anonymous fn/1 in :elixir_compiler_1.__FILE__/1
animina-web-1  |     (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
animina-web-1  |     priv/repo/flag_seeds.exs:854: (file)
animina-web-1  |     (elixir 1.16.0) lib/code.ex:1485: Code.require_file/2
animina-web-1  |     (mix 1.16.0) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
animina-web-1  |     (mix 1.16.0) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
animina-web-1  |     (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
animina-web-1  |     (mix 1.16.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
animina-web-1  |     /usr/local/bin/mix:2: (file)
```

Would it be feasible to make the seeds idempotent, so you can run them multiple times?
- https://blog.appsignal.com/2019/09/10/flags-seeds-idempotency-elixir.html
- https://elixirforum.com/t/patterns-for-making-seeds-idempotent/58299

Or does it maybe not make sense to run the seeds automatically? Would mean one more thing to think about then though, every time you run `docker-compose build` to get a clean slate.

**Comment by wintermeyer** [comment]
> Or does it maybe not make sense to run the seeds automatically?

It probably does. I'll create a migration to run the seeds: #95

**Comment by philipp-kempgen** [comment]
A migration was my first thought too.
But some people oppose running seeds in migrations:
https://elixirforum.com/t/seeds-as-migrations/20490/4
Really depends on what kind of seeds are added.
I.e. is this example data or an integral part of the system. Not sure.

**Comment by wintermeyer** [comment]
> A migration was my first thought too.
> But some people oppose running seeds in migrations:

I know but I don't care. I am not going to participate in that war.

**Pull request merged**
