### PR TITLE
Refactor/translations, closes #1071, closes #1072, closes #1073

### LINKED ISSUE #1071: Add migrations to remove translations

### LINKED ISSUE #1072: Refactor code where translations were used

### LINKED ISSUE #1073: Remove translation resources

### PR DESCRIPTION
**Pull request by briankariuki**

### CODE REVIEW

**Comment by briankariuki** [comment]
we should merge this after po files with flag and category translations are added

**Comment by wintermeyer** [comment]
> we should merge this after po files with flag and category translations are added

Do we have the English po files? Where?

**Comment by briankariuki** [comment]
> > we should merge this after po files with flag and category translations are added
> 
> Do we have the English po files? Where?

No. We have flags.txt and the seed_flags migration with the german and english translations

**Comment by wintermeyer** [comment]
@briankariuki But ist should already work or not? Just only for English right now. Because than we can merge and create a separate issue for the po files. Since we are beta I would be fine with this approach.

**Comment by briankariuki** [comment]
> @briankariuki But ist should already work or not? Just only for English right now. Because than we can merge and create a separate issue for the po files. Since we are beta I would be fine with this approach.

Right now it will just show the english name of the flag/category as it is in the database.

**Comment by wintermeyer** [comment]
> Right now it will just show the english name of the flag/category as it is in the database.

That is good enough. I prefer to take it online sooner rather than later. I'll take care of the German translation later.

**Comment by wintermeyer** [comment]
@briankariuki Please request a review when you feel this PR is production ready (all but the German translations).

**Review by wintermeyer — APPROVED** [review]

**Pull request merged**
