### PR TITLE
Feature/anonymous user actions , closes  #400

### LINKED ISSUE #400: Anonymous User Actions
- When an anonymous user views a profile and likes it , they should be redirected to the sign up page then the action should be perfomed , currently the user is just redirected back to the home page

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
- This implimentation is for when an anonymous user clicks on the heart icon when they visit a profile , the flow is they will be taken to the sign up page and login page , and if they are succesfully authenticated , the like action is performed and that user likes the profile he/she had clicked on before as shown in the video below
- The user is now redirected back to the root page and gets a flash message
- 

https://github.com/animina-dating/animina/assets/86654131/cb02066e-ca96-4ebc-bb1d-91d3199877d0

https://github.com/animina-dating/animina/assets/86654131/99be139e-c049-4d32-a775-704de19ffee6

### CODE REVIEW

**Review by wintermeyer — APPROVED** [review]

**Review by wintermeyer — CHANGES_REQUESTED** [review]
If the user clicks on the heart and gets as a result the registration page he/she doesn't know what happened. We have to display a flash message "You need to login or register first"

And it makes more sense to redirect to the log-in page. It is a close call but log-in makes a bit more sense.

**Comment by MICHAELMUNAVU83** [comment]
Yes , that makes sense , let me work on these changes

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , is there any configuration that was done to the flash group of `/sign-in` , I see the flash when I redirect to the root page , but not when  I redirect to `/sign-in`.

For the root page , I have

```
 def handle_event("redirect_to_login_after_action", _params, socket) do
    {:noreply,
     socket
     |> put_flash(:info, "You have to register or log in before liking a profile.")
     |> push_redirect(to: ~p"/")}
  end
```

and I get 

https://github.com/animina-dating/animina/assets/86654131/ff7ae968-44da-4bee-945d-8260fe74ae09



and for sign-in redirect , I have 

```
 def handle_event("redirect_to_login_after_action", _params, socket) do
    {:noreply,
     socket
     |> put_flash(:info, "You have to register or log in before liking a profile.")
     |> push_redirect(to: ~p"/sign-in/")}
  end
```

but I see no flash


https://github.com/animina-dating/animina/assets/86654131/020e48e2-7bdf-4c37-aacb-f09adfa60b1b

**Comment by wintermeyer** [comment]
> is there any configuration that was done to the flash group of `/sign-in`

I have no idea. 🤷‍♂️

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 When in doubt: Fix what you can fix and create an issue for the bug. Sometimes a good nights sleep helps. Actually very often.

**Comment by MICHAELMUNAVU83** [comment]
Thanks , will do

**Pull request merged**
