### PR TITLE
Feature/desktop version of root , closes #149

### LINKED ISSUE #149: Improve Desktop Version of /
Please improve the desktop view for this page and add a dark mode version.

Bildschirmfoto 2024-03-22 um 13 00 28

Please don't start this issue before #143 is fixed.

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
@wintermeyer  ,  Hello , I completed the dark and desktop version of / , it is now as such

Screenshot 2024-03-26 at 05 55 32
Screenshot 2024-03-26 at 05 55 26
Screenshot 2024-03-26 at 05 55 04
Screenshot 2024-03-26 at 05 54 40

### CODE REVIEW

**Comment by wintermeyer** [comment]
@xamiam I need you help. Again! 😉 I am not a big fan of this dark mode. It is ok but I am not thinking "I am loving it". Why? Do you have an idea how to improve it? It the problem the general design or just the dark mode version?

**Comment by xamiam** [comment]
Well... I guess the dark version does not feel as uplifting as the other version. Generally dark mode is a nice feature. It may feel better with higher contrasts and a general design update. I'd recommend a couple of warm, bright colours for links. Maybe also change the dark blue to a real black for contrast. What about a colorful logo?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should I add the pure black background , how would you suggest?

**Comment by wintermeyer** [comment]
> @wintermeyer , should I add the pure black background , how would you suggest?

Let’s give it a try.

**Comment by xamiam** [comment]
A little background on the colours of dark mode:

https://blog.tbhcreative.com/dark-mode-design-14-examples-of-black/

**Comment by MICHAELMUNAVU83** [comment]
Which one looks better here @wintermeyer  @xamiam  
Screenshot 2024-03-26 at 16 54 34

Screenshot 2024-03-26 at 16 53 29

**Comment by wintermeyer** [comment]
I am still not really happy with the result but let's move forward and come back in the future when somebody has a better idea.

**Pull request merged**
