### PR TITLE
Feature/desktop version of /profile/potential partner , closes #148

### LINKED ISSUE #148: Improve Desktop Version of /profile/potential-partner
Please improve the desktop view for this page and add a dark mode version.

Bildschirmfoto 2024-03-22 um 12 57 47

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
- In this PR , I worked on the desktop version of /profile/potential-partner , I have set a width of 80% on desktop devices as I feel having 100% would be an overkill . I will appreciate your advise on this , below are both screens in dark and light mode .

@wintermeyer  , I decided to go with the 2 column solution , have a look below 
Screenshot 2024-03-24 at 06 19 38

### CODE REVIEW

**Review by wintermeyer — CHANGES_REQUESTED** [review]
Not a big fan of the one column solution for the desktop. Can we use the real estate better and do a two or three column solution? I am open to other solutions too.

**Comment by MICHAELMUNAVU83** [comment]
> Not a big fan of the one column solution for the desktop. Can we use the real estate better and do a two or three column solution? I am open to other solutions too.

Okay , would you like me to fill the whole page then , we'd probably have a 3 column solution, or have the full width remain as is and impliment a 2 column solution?

**Comment by wintermeyer** [comment]
> Okay , would you like me to fill the whole page then , we'd probably have a 3 column solution, or have the full width remain as is and impliment a 2 column solution?

Surprise me. Have a look at the other pages and think of a concept which works for all of the registration process. I have no set idea for this problem.

**Comment by wintermeyer** [comment]
@xamiam In case you have time you I'd appreciate your opinion about this problem/design.

**Comment by xamiam** [comment]
Yes, sure! How about making it responsive columns? Just change the first radio element to a dropdown and you'll get 6 elements that resolve nicely in 3, 2 and 1 column(s). 
3 for desktop, 2 for tablet and alike, 1 for mobile.

**Comment by wintermeyer** [comment]
> you'll get 6 elements

The number of elements on this page is not fixed yet. We might add or delete some. Very fluent situation.

**Comment by xamiam** [comment]
Sure. Could still have responsive columns for now. Not a big deal to change later on.

**Pull request merged**
